include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering
    - curly_braces_in_flow_control_structures

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - lib/*.g.dart
    - lib/*.freezed.dart