name: summit
description: A new Flutter package project.
version: 0.0.5
#homepage:

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  url_launcher: ^6.2.6
  map_launcher: ^3.3.0

flutter: